apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: about-cert
  namespace: about
spec:
  secretName: about-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  dnsNames:
    - about.jarnomets.com
