// Sphere renderer using WebGPU with geometry generated by Rust WASM

// ── Filter config – can be updated at runtime per page ───────────────────────
export interface BackgroundFilter {
  /** Torus rotation speed multiplier (default 1.0) */
  speed: number;
  /** Ordered-dither ink density – 0 = no dots, 1 = fully filled (default 0.55) */
  opacity: number;
  /** RGB ink colour for the dither dots (default [0.55, 0.75, 1.0]) */
  color: [number, number, number];
  /** Rendering style: 'dither' (ordered Bayer dots), 'noise-dither' (hash noise, midway density), or 'wireframe' (lines) */
  style?: 'dither' | 'noise-dither' | 'wireframe';
  /** Dither density multiplier (0..1). Lower = fewer dots; 0.0 = very sparse, 1.0 = dense */
  ditherDensity?: number;
  /** Geometry resolution used to generate the torus (WASM or TS). Lower = fewer dots */
  radialSegments?: number;
  tubularSegments?: number;
}

const DEFAULT_FILTER: BackgroundFilter = {
  speed:         1.0,
  opacity:       0.55,
  color:         [0.55, 0.75, 1.0],
  // Default to dither (dot style) — matches the home page and the live site.
  // Individual pages override this via useBackground().
  style:         'dither',
  ditherDensity: 0.38,
  radialSegments: 70,
  tubularSegments: 50,
};

/** Live filter – mutate its fields to change the look without restarting. */
export const backgroundFilter: BackgroundFilter = { ...DEFAULT_FILTER };

const SHADER = /* wgsl */ `
struct Uniforms {
  mvp       : mat4x4<f32>,
  model     : mat4x4<f32>,
  lightPos  : vec4<f32>,
  viewPos   : vec4<f32>,
  // x=opacity/ink-weight, yzw=ink colour
  tint      : vec4<f32>,
  // params.x = dither density (0..1)
  params    : vec4<f32>,
}

@group(0) @binding(0) var<uniform> u : Uniforms;

struct VIn {
  @location(0) position : vec3<f32>,
  @location(1) normal   : vec3<f32>,
}

struct VOut {
  @builtin(position) clipPos    : vec4<f32>,
  @location(0)       worldPos   : vec3<f32>,
  @location(1)       worldNorm  : vec3<f32>,
}

@vertex
fn vs_main(v: VIn) -> VOut {
  var out : VOut;
  out.clipPos   = u.mvp * vec4<f32>(v.position, 1.0);
  out.worldPos  = (u.model * vec4<f32>(v.position, 1.0)).xyz;
  out.worldNorm = normalize((u.model * vec4<f32>(v.normal, 0.0)).xyz);
  return out;
}

// ── 4×4 Bayer ordered-dither matrix (values 0–15, normalised to 0–1) ─────────
fn bayer4(px: vec2<u32>) -> f32 {
  const M = array<u32, 16>(
     0u,  8u,  2u, 10u,
    12u,  4u, 14u,  6u,
     3u, 11u,  1u,  9u,
    15u,  7u, 13u,  5u,
  );
  let idx = (px.y % 4u) * 4u + (px.x % 4u);
  return f32(M[idx]) / 16.0;
}

// ── Integer hash noise – spatially uncorrelated, no visible grid pattern ─────
fn hash2(px: vec2<u32>) -> f32 {
  var h = px.x * 1664525u + px.y * 22695477u + 1013904223u;
  h ^= h >> 16u;
  h *= 0x45d9f3bu;
  h ^= h >> 16u;
  return f32(h) / f32(0xffffffffu);
}

@fragment
fn fs_main(in: VOut) -> @location(0) vec4<f32> {
  let lightDir  = normalize(u.lightPos.xyz - in.worldPos);
  let viewDir   = normalize(u.viewPos.xyz  - in.worldPos);
  let halfDir   = normalize(lightDir + viewDir);

  // Blinn-Phong luminance (0→1)
  let ambient   = 0.10;
  let diff      = max(dot(in.worldNorm, lightDir), 0.0);
  let spec      = pow(max(dot(in.worldNorm, halfDir), 0.0), 48.0) * 0.55;
  let lum       = clamp(ambient + diff * 0.85 + spec, 0.0, 1.0);

  let inkWeight = u.tint.x;
  let density   = clamp(u.params.x, 0.0, 1.0);
  let boost     = 1.5 + density * 2.0;
  let scaled    = lum * inkWeight * boost;

  let px = vec2<u32>(u32(in.clipPos.x), u32(in.clipPos.y));

  // params.y selects dither mode: 0 = ordered Bayer, 1 = hash noise
  let useNoise = u.params.y > 0.5;
  let threshold = select(bayer4(px), hash2(px), useNoise);

  if scaled <= threshold {
    discard;
  }

  let ink = u.tint.yzw;
  return vec4<f32>(ink, 1.0);
}
`;

// ── Quaternion helpers ────────────────────────────────────────────────────────

type Quat = [number, number, number, number]; // x y z w

function quatIdentity(): Quat { return [0, 0, 0, 1]; }

function quatMul(a: Quat, b: Quat): Quat {
  const [ax, ay, az, aw] = a;
  const [bx, by, bz, bw] = b;
  return [
    aw*bx + ax*bw + ay*bz - az*by,
    aw*by - ax*bz + ay*bw + az*bx,
    aw*bz + ax*by - ay*bx + az*bw,
    aw*bw - ax*bx - ay*by - az*bz,
  ];
}

/** Build a quaternion from axis (must be unit) + angle (radians). */
function quatFromAxisAngle(ax: number, ay: number, az: number, angle: number): Quat {
  const s = Math.sin(angle / 2);
  return [ax * s, ay * s, az * s, Math.cos(angle / 2)];
}

/** Normalise a quaternion in-place. */
function quatNorm(q: Quat): Quat {
  const len = Math.sqrt(q[0]*q[0] + q[1]*q[1] + q[2]*q[2] + q[3]*q[3]);
  return len > 1e-9 ? [q[0]/len, q[1]/len, q[2]/len, q[3]/len] : quatIdentity();
}

/** Convert quaternion to column-major 4×4 rotation matrix. */
function quatToMat4(q: Quat): Float32Array {
  const [x, y, z, w] = q;
  const m = new Float32Array(16);
  m[0]  = 1 - 2*(y*y + z*z);
  m[1]  =     2*(x*y + w*z);
  m[2]  =     2*(x*z - w*y);
  m[4]  =     2*(x*y - w*z);
  m[5]  = 1 - 2*(x*x + z*z);
  m[6]  =     2*(y*z + w*x);
  m[8]  =     2*(x*z + w*y);
  m[9]  =     2*(y*z - w*x);
  m[10] = 1 - 2*(x*x + y*y);
  m[15] = 1;
  return m;
}

// ── tiny mat4 helpers (column-major) ─────────────────────────────────────────

function mat4Mul(a: Float32Array, b: Float32Array): Float32Array {
  const out = new Float32Array(16);
  for (let row = 0; row < 4; row++) {
    for (let col = 0; col < 4; col++) {
      let sum = 0;
      for (let k = 0; k < 4; k++) {
        sum += a[k * 4 + row] * b[col * 4 + k];
      }
      out[col * 4 + row] = sum;
    }
  }
  return out;
}

function perspective(fovY: number, aspect: number, near: number, far: number): Float32Array {
  const f = 1.0 / Math.tan(fovY / 2);
  const nf = 1 / (near - far);
  const m = new Float32Array(16);
  m[0]  = f / aspect;
  m[5]  = f;
  m[10] = (far + near) * nf;
  m[11] = -1;
  m[14] = 2 * far * near * nf;
  return m;
}

function lookAt(eye: [number, number, number], center: [number, number, number], up: [number, number, number]): Float32Array {
  const fx = center[0] - eye[0], fy = center[1] - eye[1], fz = center[2] - eye[2];
  const flen = Math.sqrt(fx*fx+fy*fy+fz*fz);
  const f0 = fx/flen, f1 = fy/flen, f2 = fz/flen;
  const sx = f1*up[2]-f2*up[1], sy = f2*up[0]-f0*up[2], sz = f0*up[1]-f1*up[0];
  const slen = Math.sqrt(sx*sx+sy*sy+sz*sz);
  const s0 = sx/slen, s1 = sy/slen, s2 = sz/slen;
  const u0 = s1*f2-s2*f1, u1 = s2*f0-s0*f2, u2 = s0*f1-s1*f0;
  const m = new Float32Array(16);
  m[0]=s0; m[4]=s1; m[8]=s2;  m[12]=-(s0*eye[0]+s1*eye[1]+s2*eye[2]);
  m[1]=u0; m[5]=u1; m[9]=u2;  m[13]=-(u0*eye[0]+u1*eye[1]+u2*eye[2]);
  m[2]=-f0;m[6]=-f1;m[10]=-f2;m[14]= (f0*eye[0]+f1*eye[1]+f2*eye[2]);
  m[15]=1;
  return m;
}

function rotateX(angle: number): Float32Array {
  const m = new Float32Array(16);
  const c = Math.cos(angle), s = Math.sin(angle);
  m[0]=1;
  m[5]=c;  m[9]=-s;
  m[6]=s;  m[10]=c;
  m[15]=1;
  return m;
}

function rotateY(angle: number): Float32Array {
  const m = new Float32Array(16);
  const c = Math.cos(angle), s = Math.sin(angle);
  m[0]=c; m[8]=s;
  m[5]=1;
  m[2]=-s;m[10]=c;
  m[15]=1;
  return m;
}

function rotateZ(angle: number): Float32Array {
  const m = new Float32Array(16);
  const c = Math.cos(angle), s = Math.sin(angle);
  m[0]=c; m[4]=-s;
  m[1]=s; m[5]=c;
  m[10]=1;
  m[15]=1;
  return m;
}

// ── Renderer ──────────────────────────────────────────────────────────────────

export async function initSphereRenderer(canvas: HTMLCanvasElement): Promise<() => void> {
  if (!navigator.gpu) {
    throw new Error('WebGPU is not supported in this browser.');
  }

  // Dev-time diagnostics: log which source is used and current filter settings
  // Only run in non-production so we don't spam logs on live.
  const isDev = typeof import.meta !== 'undefined' && (import.meta as any).env && (import.meta as any).env.MODE !== 'production';
  if (isDev) {
    // eslint-disable-next-line no-console
    console.info('[sphere-renderer] init requested. backgroundFilter:', JSON.parse(JSON.stringify(backgroundFilter)));
  }

  // Try loading the WASM module first (fast and native in many builds).
  // If that fails (not built / not present), fall back to the TS generator.
  let torus_vertices: (radial_segments: number, tubular_segments: number, radius: number, tube: number) => Float32Array;
  let torus_indices: (radial_segments: number, tubular_segments: number) => Uint32Array;

  try {
    const wasmUrl = new URL('/wasm-sphere/wasm_sphere.js', import.meta.url).href;
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const wasmMod = await import(/* @vite-ignore */ wasmUrl) as any;
    if (wasmMod && typeof wasmMod.default === 'function') {
      await wasmMod.default(); // initialise WASM if present
    }
    torus_vertices = wasmMod?.torus_vertices;
    torus_indices  = wasmMod?.torus_indices;
    if (isDev) console.info('[sphere-renderer] using WASM module for torus geometry');
  } catch (e) {
    // WASM not available or failed at runtime — fall back to TypeScript generator.
    const tsMod = await import('./torus-geometry');
    torus_vertices = tsMod.torus_vertices;
    torus_indices  = tsMod.torus_indices;
    if (isDev) console.info('[sphere-renderer] WASM load failed — using TS fallback for torus geometry', e);
  }

  // Copy from WASM memory into regular ArrayBuffers (WASM may use SharedArrayBuffer)
  // torus_vertices/indices may be either WASM exports (already returning typed arrays)
  // or the TS fallback which returns typed arrays as well.
  const radial = backgroundFilter.radialSegments ?? 64;
  const tubular = backgroundFilter.tubularSegments ?? 32;
  const vertData   = torus_vertices(radial, tubular, 1.2, 0.4);
  const indexData  = torus_indices(radial, tubular);
  let indexCount = indexData.length;

  // Ensure we have proper TypedArray views for the GPU writeBuffer call.
  // The WASM-generated exports may return exotic views; coerce when necessary.
  const vertArray: Float32Array = (ArrayBuffer.isView(vertData) && (vertData instanceof Float32Array))
    ? vertData
    : new Float32Array(vertData as ArrayLike<number>);

  const indexArray: Uint32Array = (ArrayBuffer.isView(indexData) && (indexData instanceof Uint32Array))
    ? indexData
    : new Uint32Array(indexData as ArrayLike<number>);

  // ── WebGPU init ─────────────────────────────────────────────────────────────

  const adapter = await navigator.gpu.requestAdapter({ powerPreference: 'high-performance' });
  if (!adapter) throw new Error('No GPU adapter found.');
  const device = await adapter.requestDevice();
  const queue  = device.queue;

  const context = canvas.getContext('webgpu') as GPUCanvasContext;
  const format  = navigator.gpu.getPreferredCanvasFormat();

  context.configure({ device, format, alphaMode: 'premultiplied' });

  // ── Buffers ──────────────────────────────────────────────────────────────────

  // Vertex / index buffers are mutable so we can regenerate geometry at runtime
  let vb = device.createBuffer({
    size: vertArray.byteLength,
    usage: GPUBufferUsage.VERTEX | GPUBufferUsage.COPY_DST,
  });
  // Use the underlying ArrayBuffer to avoid type issues with some lib GPU typings.
  device.queue.writeBuffer(vb, 0, vertArray.buffer, vertArray.byteOffset, vertArray.byteLength);

  let ib = device.createBuffer({
    size: indexArray.byteLength,
    usage: GPUBufferUsage.INDEX | GPUBufferUsage.COPY_DST,
  });
  device.queue.writeBuffer(ib, 0, indexArray.buffer, indexArray.byteOffset, indexArray.byteLength);

  // Build a line-list index buffer for wireframe rendering (dedup edges)
  const edgeSet = new Set<string>();
  const lineIndices: number[] = [];
  for (let t = 0; t < indexArray.length; t += 3) {
    const a = indexArray[t], b = indexArray[t+1], c = indexArray[t+2];
    const edges = [[a,b],[b,c],[c,a]];
    for (const [x,y] of edges) {
      const mn = x < y ? x : y;
      const mx = x < y ? y : x;
      const key = mn + ',' + mx;
      if (!edgeSet.has(key)) {
        edgeSet.add(key);
        lineIndices.push(mn, mx);
      }
    }
  }

  const lineIndexArray = new Uint32Array(lineIndices);
  let ibLine = device.createBuffer({ size: lineIndexArray.byteLength, usage: GPUBufferUsage.INDEX | GPUBufferUsage.COPY_DST });
  device.queue.writeBuffer(ibLine, 0, lineIndexArray.buffer, lineIndexArray.byteOffset, lineIndexArray.byteLength);
  let lineIndexCount = lineIndexArray.length;

  // Track last-used geometry resolution so we can regenerate if a page changes it.
  let lastRadial = radial;
  let lastTubular = tubular;

  // Helper: regenerate geometry buffers from the torus generator (WASM or TS)
  function regenerateGeometry(newRadial: number, newTubular: number) {
    try {
      const vdata = torus_vertices(newRadial, newTubular, 1.2, 0.4);
      const idata = torus_indices(newRadial, newTubular);

      const vArr: Float32Array = (ArrayBuffer.isView(vdata) && (vdata instanceof Float32Array))
        ? vdata
        : new Float32Array(vdata as ArrayLike<number>);

      const iArr: Uint32Array = (ArrayBuffer.isView(idata) && (idata instanceof Uint32Array))
        ? idata
        : new Uint32Array(idata as ArrayLike<number>);

      // Destroy old GPU buffers (safe no-op in older impls) then recreate with new sizes
      try { vb.destroy(); } catch (e) { /* ignore */ }
      try { ib.destroy(); } catch (e) { /* ignore */ }
      try { ibLine.destroy(); } catch (e) { /* ignore */ }

      vb = device.createBuffer({ size: vArr.byteLength, usage: GPUBufferUsage.VERTEX | GPUBufferUsage.COPY_DST });
      device.queue.writeBuffer(vb, 0, vArr.buffer, vArr.byteOffset, vArr.byteLength);

      ib = device.createBuffer({ size: iArr.byteLength, usage: GPUBufferUsage.INDEX | GPUBufferUsage.COPY_DST });
      device.queue.writeBuffer(ib, 0, iArr.buffer, iArr.byteOffset, iArr.byteLength);

      // rebuild deduplicated line indices
      const edgeSet2 = new Set<string>();
      const lineIdx2: number[] = [];
      for (let t = 0; t < iArr.length; t += 3) {
        const a = iArr[t], b = iArr[t+1], c = iArr[t+2];
        const edges = [[a,b],[b,c],[c,a]];
        for (const [x,y] of edges) {
          const mn = x < y ? x : y;
          const mx = x < y ? y : x;
          const key = mn + ',' + mx;
          if (!edgeSet2.has(key)) { edgeSet2.add(key); lineIdx2.push(mn, mx); }
        }
      }

      const lineArr2 = new Uint32Array(lineIdx2);
      ibLine = device.createBuffer({ size: lineArr2.byteLength, usage: GPUBufferUsage.INDEX | GPUBufferUsage.COPY_DST });
      device.queue.writeBuffer(ibLine, 0, lineArr2.buffer, lineArr2.byteOffset, lineArr2.byteLength);
      lineIndexCount = lineArr2.length;

      // update counts
      // indexCount variable is const above; replace by writing to outer-scoped variable via closure
      indexCount = iArr.length;
      // store the last-used values
      lastRadial = newRadial;
      lastTubular = newTubular;
      if (isDev) console.info('[sphere-renderer] regenerated geometry', { newRadial, newTubular, indexCount: iArr.length, lineIndexCount: lineArr2.length });
    } catch (err) {
      if (isDev) console.warn('[sphere-renderer] failed to regenerate geometry', err);
    }
  }

  const UNIFORM_SIZE = 4 * (16 + 16 + 4 + 4 + 4 + 4); // 2× mat4 + 4× vec4 (lightPos, viewPos, tint, params)
  const ub = device.createBuffer({
    size: UNIFORM_SIZE,
    usage: GPUBufferUsage.UNIFORM | GPUBufferUsage.COPY_DST,
  });

  // ── Depth texture ────────────────────────────────────────────────────────────

  let depthTex = createDepthTexture(device, canvas.width, canvas.height);

  // ── Pipeline ─────────────────────────────────────────────────────────────────

  const shader = device.createShaderModule({ code: SHADER });

  const bgl = device.createBindGroupLayout({
    entries: [{
      binding: 0,
      visibility: GPUShaderStage.VERTEX | GPUShaderStage.FRAGMENT,
      buffer: { type: 'uniform' },
    }],
  });

  const bg = device.createBindGroup({
    layout: bgl,
    entries: [{ binding: 0, resource: { buffer: ub } }],
  });

  const pipeline = device.createRenderPipeline({
    layout: device.createPipelineLayout({ bindGroupLayouts: [bgl] }),
    vertex: {
      module: shader,
      entryPoint: 'vs_main',
      buffers: [{
        arrayStride: 6 * 4,
        attributes: [
          { shaderLocation: 0, offset: 0,      format: 'float32x3' },
          { shaderLocation: 1, offset: 3 * 4,  format: 'float32x3' },
        ],
      }],
    },
    fragment: {
      module: shader,
      entryPoint: 'fs_main',
      targets: [{
        format,
        blend: {
          // Standard src-over: opaque ink dots composite over the transparent background
          color: { srcFactor: 'src-alpha', dstFactor: 'one-minus-src-alpha', operation: 'add' },
          alpha: { srcFactor: 'one',       dstFactor: 'one-minus-src-alpha', operation: 'add' },
        },
      }],
    },
    primitive: {
      topology: 'triangle-list',
      cullMode: 'back',
    },
    depthStencil: {
      format: 'depth24plus',
      depthWriteEnabled: true,
      depthCompare: 'less',
    },
  });

  // --- Wireframe pipeline (line-list) -----------------------------------
  // Simple shader module for lines: output a solid ink colour from tint.yzw
  const LINE_SHADER = /* wgsl */ `
struct Uniforms { mvp: mat4x4<f32>, model: mat4x4<f32>, lightPos: vec4<f32>, viewPos: vec4<f32>, tint: vec4<f32>, params: vec4<f32>, }
@group(0) @binding(0) var<uniform> u : Uniforms;

struct VIn { @location(0) position : vec3<f32>, @location(1) normal : vec3<f32>, }
struct VOut { @builtin(position) clipPos : vec4<f32>, }

@vertex
fn vs_main(v : VIn) -> VOut {
  var out : VOut;
  out.clipPos = u.mvp * vec4<f32>(v.position, 1.0);
  return out;
}

@fragment
fn fs_main() -> @location(0) vec4<f32> {
  let ink = u.tint.yzw;
  return vec4<f32>(ink, 1.0);
}
`;

  const lineShader = device.createShaderModule({ code: LINE_SHADER });
  const pipelineLine = device.createRenderPipeline({
    layout: device.createPipelineLayout({ bindGroupLayouts: [bgl] }),
    vertex: {
      module: lineShader,
      entryPoint: 'vs_main',
      buffers: [{ arrayStride: 6 * 4, attributes: [ { shaderLocation: 0, offset: 0, format: 'float32x3' }, { shaderLocation: 1, offset: 3 * 4, format: 'float32x3' } ] }],
    },
    fragment: { module: lineShader, entryPoint: 'fs_main', targets: [{ format, blend: { color: { srcFactor: 'src-alpha', dstFactor: 'one-minus-src-alpha', operation: 'add' }, alpha: { srcFactor: 'one', dstFactor: 'one-minus-src-alpha', operation: 'add' } } }] },
    primitive: { topology: 'line-list', cullMode: 'none' },
    depthStencil: { format: 'depth24plus', depthWriteEnabled: true, depthCompare: 'less' },
  });

  // ── Resize handler ───────────────────────────────────────────────────────────

  const observer = new ResizeObserver(() => {
    const w = canvas.clientWidth  * devicePixelRatio | 0;
    const h = canvas.clientHeight * devicePixelRatio | 0;
    if (w !== canvas.width || h !== canvas.height) {
      canvas.width  = w || 1;
      canvas.height = h || 1;
      depthTex.destroy();
      depthTex = createDepthTexture(device, canvas.width, canvas.height);
    }
  });
  observer.observe(canvas);

  // ── Cursor-reactive / idle-spin mode ────────────────────────────────────────
  //
  // Two modes that blend smoothly:
  //
  //  CURSOR mode  – mouse has moved within the last IDLE_TIMEOUT seconds.
  //                 Auto-spin is frozen; the torus reacts only to cursor position.
  //                 • angle of cursor from viewport centre → rotation axis
  //                 • distance from centre (0–1)          → spin speed
  //
  //  IDLE mode    – no mouse movement for IDLE_TIMEOUT seconds.
  //                 Classic lazy auto-spin resumes from where it paused.
  //
  // The blend is a smooth 0→1 ramp over FADE_DURATION seconds so the switch
  // between modes is never jarring.

  const IDLE_TIMEOUT  = 5.0;   // seconds of no movement before idle kicks in
  const FADE_DURATION = 1.5;   // seconds to cross-fade between modes
  const CURSOR_EMA    = 0.06;  // EMA factor for smoothing cursor position
  const MAX_CURSOR_SPEED = 2.8; // rad/s at edge of screen

  /** Timestamp (ms) of the most recent mousemove event. */
  let lastMoveMs = -Infinity;

  /** Raw target cursor vector, normalised [-1,1]×[-1,1]. */
  let targetCX = 0;
  let targetCY = 0;
  /** EMA-smoothed cursor vector. */
  let smoothCX = 0;
  let smoothCY = 0;

  function onMouseMove(e: MouseEvent) {
    lastMoveMs = performance.now();
    targetCX   =  (e.clientX / window.innerWidth  - 0.5) * 2;
    targetCY   = -(e.clientY / window.innerHeight - 0.5) * 2; // Y-up
  }

  function onMouseLeave() {
    // Treat leaving the page as "no cursor" – accelerate idle transition
    lastMoveMs = -Infinity;
    targetCX   = 0;
    targetCY   = 0;
  }

  document.addEventListener('mousemove',  onMouseMove);
  document.addEventListener('mouseleave', onMouseLeave);

  // ── Render loop ──────────────────────────────────────────────────────────────

  const eye: [number, number, number] = [0, 1.5, 3.5];
  let rafId: number;
  let lastFrameMs = performance.now();

  // Cursor-driven accumulated orientation quaternion.
  let cursorQuat: Quat = quatIdentity();

  // Auto-spin time offset: we freeze this while in cursor mode so the spin
  // resumes seamlessly from the same angle when idle mode returns.
  let autoSpinT   = 0.0;   // effective time for the auto-spin angle
  let idleWeight  = 1.0;   // 0 = full cursor mode, 1 = full idle mode

  function frame() {
    const nowMs = performance.now();
    const dt    = Math.min((nowMs - lastFrameMs) / 1000, 0.1);
    lastFrameMs = nowMs;

    // ── Compute idle blend weight ────────────────────────────────────────────
    const idleSince = (nowMs - lastMoveMs) / 1000; // seconds since last move
    // Target: 0 if cursor recently moved, 1 if idle long enough
    const targetIdle = idleSince >= IDLE_TIMEOUT ? 1.0 : 0.0;
    // Ease toward target at a rate of 1/FADE_DURATION per second
    idleWeight += (targetIdle - idleWeight) * Math.min(dt / FADE_DURATION, 1.0);

    // ── Advance auto-spin time only proportional to idle weight ─────────────
    autoSpinT += dt * backgroundFilter.speed * idleWeight;

    // ── EMA-smooth cursor ────────────────────────────────────────────────────
    // When idle, ease the cursor target back toward zero so the cursor
    // influence gradually vanishes.
    const effectiveTargetX = targetCX * (1 - idleWeight);
    const effectiveTargetY = targetCY * (1 - idleWeight);
    smoothCX += (effectiveTargetX - smoothCX) * CURSOR_EMA;
    smoothCY += (effectiveTargetY - smoothCY) * CURSOR_EMA;

    // ── Apply cursor rotation ────────────────────────────────────────────────
    const curLen = Math.sqrt(smoothCX * smoothCX + smoothCY * smoothCY);
    if (curLen > 1e-4) {
      const dist   = Math.min(curLen, 1.0);
      // Use sqrt mapping so speed grows quickly near center but tapers off
      // toward the edges — feels much more natural than linear.
      const distMapped = Math.sqrt(dist);
      // Rotation axis perpendicular to cursor direction: (-cy, cx, 0)
      const axisX  = -smoothCY / curLen;
      const axisY  =  smoothCX / curLen;
      // Normalise by screen diagonal (in CSS pixels) so the torus spins at
      // the same perceived speed regardless of screen resolution / size.
      const diagPx  = Math.sqrt(window.innerWidth * window.innerWidth + window.innerHeight * window.innerHeight);
      const refDiag = 1920; // reference diagonal for a typical 1080p / 1440p screen
      const resScale = refDiag / Math.max(diagPx, 400);
      const speed  = distMapped * MAX_CURSOR_SPEED * backgroundFilter.speed * (1 - idleWeight) * resScale;
      const dq     = quatFromAxisAngle(axisX, axisY, 0, speed * dt);
      cursorQuat   = quatNorm(quatMul(dq, cursorQuat));
    }

    const aspect = canvas.width / canvas.height;
    const proj   = perspective(Math.PI / 4, aspect, 0.1, 100.0);
    const view   = lookAt(eye, [0, 0, 0], [0, 1, 0]);

    // Auto-spin model (uses frozen/thawed autoSpinT instead of wall clock)
    const slantX    = rotateX(Math.PI / 6);
    const slantZ    = rotateZ(Math.PI / 8);
    const spinY     = rotateY(autoSpinT * 1.2);
    const autoModel = mat4Mul(mat4Mul(spinY, slantX), slantZ);

    // Cursor quaternion layered on top (fades out as idleWeight → 1)
    const cursorMat = quatToMat4(cursorQuat);
    const model     = mat4Mul(cursorMat, autoModel);
    const mvp       = mat4Mul(mat4Mul(proj, view), model);

    const { opacity, color, ditherDensity, style } = backgroundFilter;
    const noiseMode = style === 'noise-dither' ? 1.0 : 0.0;
    // pack uniforms: mvp (16), model (16), lightPos (4), viewPos (4), tint (4), params (4)
    // params: x=ditherDensity, y=noiseMode (0=Bayer, 1=hash), zw=unused
    const uniforms = new Float32Array(16 + 16 + 4 + 4 + 4 + 4);
    uniforms.set(mvp,   0);
    uniforms.set(model, 16);
    uniforms.set([3.0, 4.0, 3.0, 1.0],                    32);
    uniforms.set([...eye, 1.0],                            36);
    uniforms.set([opacity, color[0], color[1], color[2]], 40);
    uniforms.set([ditherDensity ?? 0.45, noiseMode, 0, 0], 44);
    queue.writeBuffer(ub, 0, uniforms);

    // If a page changed the target geometry resolution, regenerate buffers now.
    const curRadial = backgroundFilter.radialSegments ?? 64;
    const curTubular = backgroundFilter.tubularSegments ?? 32;
    if (curRadial !== lastRadial || curTubular !== lastTubular) {
      regenerateGeometry(curRadial, curTubular);
    }

    const frameView = context.getCurrentTexture().createView();
    const enc   = device.createCommandEncoder();

    const rp = enc.beginRenderPass({
      colorAttachments: [{
        view: frameView,
        clearValue: { r: 0, g: 0, b: 0, a: 0 },
        loadOp:  'clear',
        storeOp: 'store',
      }],
      depthStencilAttachment: {
        view: depthTex.createView(),
        depthClearValue:  1.0,
        depthLoadOp:  'clear',
        depthStoreOp: 'store',
      },
    });

    // Choose rendering style per the live backgroundFilter
    // Both 'dither' and 'noise-dither' use the triangle pipeline (shader selects the threshold fn)
    if (backgroundFilter.style === 'wireframe') {
      rp.setPipeline(pipelineLine);
      rp.setBindGroup(0, bg);
      rp.setVertexBuffer(0, vb);
      rp.setIndexBuffer(ibLine, 'uint32');
      rp.drawIndexed(lineIndexCount);
    } else {
      rp.setPipeline(pipeline);
      rp.setBindGroup(0, bg);
      rp.setVertexBuffer(0, vb);
      rp.setIndexBuffer(ib, 'uint32');
      rp.drawIndexed(indexCount);
    }
    rp.end();

    queue.submit([enc.finish()]);
    rafId = requestAnimationFrame(frame);
  }

  rafId = requestAnimationFrame(frame);

  // Return cleanup function
  return () => {
    cancelAnimationFrame(rafId);
    observer.disconnect();
    document.removeEventListener('mousemove',  onMouseMove);
    document.removeEventListener('mouseleave', onMouseLeave);
  };
}

function createDepthTexture(device: GPUDevice, w: number, h: number): GPUTexture {
  return device.createTexture({
    size: [w, h],
    format: 'depth24plus',
    usage: GPUTextureUsage.RENDER_ATTACHMENT,
  });
}
